export const GET_ALL_RESTAURANTS="http://localhost:4000"
export const POST_RESTAURANT="http://localhost:4000/restaurants/post"
export const UPDATE_RESTAURANT="http://localhost:4000/restaurants"
export const DELETE_RESTAURANT="http://localhost:4000/restaurants"
export const GET_RESTAURANT_BY_ID="http://localhost:4000/restaurant"